name: Commit Job

on:
  schedule:
    - cron: "*/45 * * * *"
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Roll Dice
        run: echo "PROCEED=$((RANDOM % 2))" > $GITHUB_ENV
        shell: bash

      - if: env.PROCEED == '0'
        name: Cancelling
        uses: andymckay/cancel-action@0.2

      - if: env.PROCEED == '0'
        name: Waiting For Cancellation
        run: sleep 60

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Apply Commit And Push
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          REPOSITORY: ${{ secrets.REPOSITORY }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_NAME: ${{ secrets.GIT_NAME }}
        run: bash run.sh